apiVersion: v1

kind: Service

metadata:
  name: user-service

spec:

  type: {{ .Values.service.user.type }}

  selector:
    app: user-service

  ports:

    - name: http

      port: {{ .Values.service.user.port }}

      targetPort: {{ .Values.service.user.targetPort }}

      protocol: TCP