apiVersion: v1

kind: Service

metadata:
  name: product-service

spec:

  type: {{ .Values.service.product.type }}

  selector:
    app: product-service

  ports:

    - name: http

      port: {{ .Values.service.product.port }}

      targetPort: {{ .Values.service.product.targetPort }}

      protocol: TCP