# ==========================================
# Replica Count
# ==========================================

replicaCount:
  frontend: 2
  user: 2
  product: 2
  order: 2


# ==========================================
# Docker Images
# ==========================================

images:

  frontend:
    repository: mokchhedul/iips_frontend
    tag: v1
    pullPolicy: IfNotPresent

  user:
    repository: mokchhedul/iips_user_service
    tag: latest
    pullPolicy: IfNotPresent

  product:
    repository: mokchhedul/iips_product_service
    tag: latest
    pullPolicy: IfNotPresent

  order:
    repository: mokchhedul/iips_order_service
    tag: latest
    pullPolicy: IfNotPresent


# ==========================================
# Container Ports
# ==========================================

ports:

  frontend: 3000

  user: 5001

  product: 5002

  order: 5003


# ==========================================
# Kubernetes Services
# ==========================================

service:

  frontend:
    type: ClusterIP
    port: 80
    targetPort: 3000

  user:
    type: ClusterIP
    port: 5001
    targetPort: 5001

  product:
    type: ClusterIP
    port: 5002
    targetPort: 5002

  order:
    type: ClusterIP
    port: 5003
    targetPort: 5003


# ==========================================
# Application Configuration
# ==========================================

app:

  corsUrl: "http://frontend-service"

  jwt:
    expiresIn: "1d"


# ==========================================
# Database Configuration
# ==========================================

database:

  userMongoUri: "mongodb+srv://mokchheduls46_db_user:mokchhedul@mlopscluster.eocbyro.mongodb.net/ecom"

  productMongoUri: "mongodb+srv://mokchheduls46_db_user:mokchhedul@mlopscluster.eocbyro.mongodb.net/product"

  orderMongoUri: "mongodb+srv://mokchheduls46_db_user:mokchhedul@mlopscluster.eocbyro.mongodb.net/order"


# ==========================================
# JWT
# ==========================================

jwt:

  secret: "super_secret_key_is_this"


# ==========================================
# Ingress
# ==========================================

ingress:
  enabled: true

  className: alb

  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip

  host: ""

  tls:
    enabled: false
    secretName: ""


# ==========================================
# Resources
# ==========================================

resources:

  frontend:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

  user:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

  product:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

  order:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi


# ==========================================
# Security
# ==========================================

securityContext:

  runAsNonRoot: false

  allowPrivilegeEscalation: false


# ==========================================
# HPA
# ==========================================

autoscaling:

  enabled: false

  minReplicas: 2

  maxReplicas: 5

  targetCPUUtilizationPercentage: 70