# {{- if .Values.ingress.enabled }}

# apiVersion: networking.k8s.io/v1

# kind: Ingress

# metadata:

#   name: {{ include "iips.fullname" . }}-ingress

#   annotations:
#     {{- with .Values.ingress.annotations }}
#     {{- toYaml . | nindent 4 }}
#     {{- end }}

# spec:

#   ingressClassName: {{ .Values.ingress.className }}

#   {{- if .Values.ingress.tls.enabled }}

#   tls:

#     - hosts:

#         - {{ .Values.ingress.host }}

#       secretName: {{ .Values.ingress.tls.secretName }}

#   {{- end }}

#   rules:

#     - host: {{ .Values.ingress.host }}

#       http:

#         paths:

#           # Frontend

#           - path: /

#             pathType: Prefix

#             backend:

#               service:

#                 name: frontend-service

#                 port:

#                   number: {{ .Values.service.frontend.port }}


#           # User API

#           - path: /api/users

#             pathType: Prefix

#             backend:

#               service:

#                 name: user-service

#                 port:

#                   number: {{ .Values.service.user.port }}


#           # Product API

#           - path: /api/products

#             pathType: Prefix

#             backend:

#               service:

#                 name: product-service

#                 port:

#                   number: {{ .Values.service.product.port }}


#           # Order API

#           - path: /api/orders

#             pathType: Prefix

#             backend:

#               service:

#                 name: order-service

#                 port:

#                   number: {{ .Values.service.order.port }}

# {{- end }}