apiVersion: v1
kind: Secret

metadata:
  name: {{ include "iips.fullname" . }}-secret

type: Opaque

stringData:

  USER_MONGO_URI: {{ .Values.database.userMongoUri | quote }}

  PRODUCT_MONGO_URI: {{ .Values.database.productMongoUri | quote }}

  ORDER_MONGO_URI: {{ .Values.database.orderMongoUri | quote }}

  JWT_SECRET: {{ .Values.jwt.secret | quote }}